---
name: Tests

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Tests

    runs-on: ubuntu-latest
    services:
      docker:
        image: docker.io/library/docker:dind@sha256:b0c1179ea32ad77bdb7b852b037e54b11022304c2f2662af1954ef53869314b2
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Compile Go source
      run: go test -c -o /dev/null ./...

    - name: Build Ginkgo CLI
      run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo

    - name: Build test image
      run: docker build --tag test:me -f test/sample/Dockerfile test/sample/data

    - name: Test
      run: |
        ginkgo run \
          --coverprofile=unit.coverprofile \
          --randomize-all \
          --randomize-suites \
          --fail-on-pending \
          --keep-going \
          --compilers=2 \
          --race \
          --trace \
          -v \
          ./...

    - name: Upload Code Coverage Profile
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: unit.coverprofile
        flags: unittests
        fail_ci_if_error: true
        verbose: false
